#!/usr/bin/env bash

set -euo pipefail

export banner="
 /\$\$   /\$\$  /\$\$\$\$\$\$  /\$\$\$\$\$\$ /\$\$\$\$\$\$\$        /\$\$\$\$\$\$\$\$ /\$\$      /\$\$ /\$\$\$\$\$\$\$\$  /\$\$\$\$\$\$  /\$\$   /\$\$  /\$\$\$\$\$\$
| \$\$\$ | \$\$ /\$\$__  \$\$|_  \$\$_/| \$\$__  \$\$      |__  \$\$__/| \$\$  /\$ | \$\$| \$\$_____/ /\$\$__  \$\$| \$\$  /\$\$/ /\$\$__  \$\$
| \$\$\$\$| \$\$| \$\$  \\ \$\$  | \$\$  | \$\$  \\ \$\$         | \$\$   | \$\$ /\$\$\$| \$\$| \$\$      | \$\$  \\ \$\$| \$\$ /\$\$/ | \$\$  \\__/
| \$\$ \$\$ \$\$| \$\$  | \$\$  | \$\$  | \$\$  | \$\$         | \$\$   | \$\$/\$\$ \$\$ \$\$| \$\$\$\$\$   | \$\$\$\$\$\$\$\$| \$\$\$\$\$/  |  \$\$\$\$\$\$
| \$\$  \$\$\$\$| \$\$  | \$\$  | \$\$  | \$\$  | \$\$         | \$\$   | \$\$\$\$_  \$\$\$\$| \$\$__/   | \$\$__  \$\$| \$\$  \$\$   \\____  \$\$
| \$\$\\  \$\$\$| \$\$  | \$\$  | \$\$  | \$\$  | \$\$         | \$\$   | \$\$\$/ \\  \$\$\$| \$\$      | \$\$  | \$\$| \$\$\\  \$\$  /\$\$  \\ \$\$
| \$\$ \\  \$\$|  \$\$\$\$\$\$/ /\$\$\$\$\$\$| \$\$\$\$\$\$\$/         | \$\$   | \$\$/   \\  \$\$| \$\$\$\$\$\$\$\$| \$\$  | \$\$| \$\$ \\  \$\$|  \$\$\$\$\$\$/
|__/  \\__/ \\______/ |______/|_______/          |__/   |__/     \\__/|________/|__/  |__/|__/  \\__/ \\______/
"

export header="
# === AUTO-GENERATED BY NOID TWEAKS ===
"

export footer="
# ========== END NOID TWEAK ==========="

get_software() {
    yad --list --checklist \
        --width=302 --height=400 \
        --multiple \
        --column=Install:Tick \
        --column=Package:text \
        --column=package_name:HD \
        false Spotify spotify-client \
        false Discord discord \
        false Obsidian obsidian \
        true Brave brave \
        false LibreWolf librewolf \
        false Cinny cinny-desktop \
        false Grayjay grayjay \
        false FreeTube freetube | awk -F '|' '{ print $3 }' | paste -sd ' ' | xargs -r alacritty --hold -e ndpm install
}
export -f get_software

install_qemu_vmm() {
    clear
    
    summary="
    This tweak will install virt-manager, in the process it will:
    - Install these deps: qemu, virt-manager, virt-viewer, dnsmasq, vde2, bridge-utils, openbsd-netcat, libguestfs
    - Enable these Runit services: libvirtd, virtlogd
    - Modify these files: /etc/libvirt/libvirtd.conf, /etc/libvirt/qemu.conf
    - Add your user to the libvirt user group.
    
    And you will need to restart for changes to take effect."
    
    libvirtd_conf="
    unix_sock_group = \"libvirt\"
    unix_sock_ro_perms = \"0777\"
    unix_sock_rw_perms = \"0770\"
    "
    
    qemu_conf="
    user = \"$USER\"
    group = \"$USER\"
    "
    
    echo "$banner"
    echo "$summary"
    
    read -p "Continue? [y/N] " -r response
    
    [[ "$response" == [yY] ]] || { echo "Cancelled." && exit 1; }
    
    sudo -v
    
    echo "Installing virtualization packages..."
    if ! sudo xbps-install -Sy qemu virt-manager virt-viewer dnsmasq vde2 bridge-utils openbsd-netcat libguestfs; then
        echo "Package installation failed. Exiting."
        exit 1
    fi
    
    echo "Starting services..."
    sudo ln -sf /etc/sv/libvirtd /var/service
    sudo ln -sf /etc/sv/virtlogd /var/service
    
    echo "Configuring libvirtd..."
    
    if grep -q 'AUTO-GENERATED BY NOID TWEAKS' /etc/libvirt/libvirtd.conf; then
        echo "Configuration already applied. Skipping setup."
    else
        echo "$header$libvirtd_conf$footer" | sudo tee -a /etc/libvirt/libvirtd.conf > /dev/null
    fi
    
    echo "Configuring qemu..."
    
    if grep -q 'AUTO-GENERATED BY NOID TWEAKS' /etc/libvirt/qemu.conf; then
        echo "Configuration already applied. Skipping setup."
    else
        echo "$header$qemu_conf$footer" | sudo tee -a /etc/libvirt/qemu.conf > /dev/null
    fi
    
    echo "Adding user to libvirt group..."
    sudo usermod -aG libvirt "$USER"
    
    echo "Setup complete. Restart your system for changes to fully take effect."
}
export -f install_qemu_vmm

oxidize_system() {
    clear
    
    summary="
    This tweak will install Rust and some useful CLIs, in the process it will:
    - Install rustup
    - Install these CLIs with Cargo: ripgrep, bat, fd-find, zoxide, eza, tealdeer, du-dust, dysk, bottom, cargo-update
    - Modify these files: ~/.zshrc, ~/.bashrc"
    
    aliases_conf="
    alias \\
      ls='eza --icons=always --group-directories-first' \\
      ll='ls -la --git' \\
      tree='ls -Ta -I \".git\"' \\
      cat='bat --style plain --color=always' \\
      cd='z' \\
      cargo-update='cargo install-update -a'
    "
    
    echo "$banner"
    echo "$summary"
    
    read -p "Continue? [y/N] " -r response
    
    [[ "$response" == [yY] ]] || { echo "Cancelled." && exit 1; }
    
    echo "Installing Rust toolchain..."
    if ! curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh; then
        echo "Rust installation failed. Exiting."
        exit 1
    fi
    
    echo "Installing CLI tools..."
    if ! ~/.cargo/bin/cargo install ripgrep bat fd-find zoxide eza tealdeer du-dust dysk bottom cargo-update; then
        echo "CLI tools installation failed. Exiting."
        exit 1
    fi
    
    echo "Adding aliases to shell configs..."
    
    if grep -q 'AUTO-GENERATED BY NOID TWEAKS' ~/.zshrc || grep -q 'AUTO-GENERATED BY NOID TWEAKS' ~/.bashrc; then
        echo "Aliases already configured. Skipping setup."
    else
        echo "$header$aliases_conf$footer" | tee -a ~/.zshrc
        echo "$header$aliases_conf$footer" | tee -a ~/.bashrc
    fi
    
    echo "Setup complete."
}
export -f oxidize_system

system_update() {
    ndpm update && ndpm upgrade -y
}
export -f system_update

yad --form --title="Welcome to Noid Linux!" --height=420 --width=1000 \
--center --text-align="left" --window-icon=/usr/share/noid-artwork/noid-logo.png \
--borders=20 \
--image="/usr/share/noid-artwork/noid-logo.png" \
--text="<span font_weight='bold' font='18' color='#d79921'>Welcome to Noid GNU/Linux</span> 
This tool provides quick access to software installation, system updates, and
setup scripts for virtualization and Rust-based tools.

Have questions or feedback? Don't hesitate to reach out.
" \
--columns=4 --align-buttons \
--field="Software Managment:LBL" " " \
--field="  Get Software!package!Get software from our custom repo:FBTN" "bash -c get_software" \
--field="  System Update!/usr/share/noid-artwork/noid-logo.png!System update.":fbtn "alacritty --hold -e bash -c system_update" \
--field="System Tweaks:LBL" " " \
--field="  Install virt-manager!virt-manager!This will execute a script to install qemu and virt-manager with all the dependencies needed for a smooth virtualization experience.":fbtn "alacritty --hold -e bash -c install_qemu_vmm" \
--field="  Oxidize Your System!/usr/share/noid-artwork/noid-logo.png!This will install a collection of Rust based utils and add a bunch of aliases to your shell config.":fbtn "alacritty --hold -e bash -c oxidize_system" \
--field="Links:LBL" " " \
--field="Source Code!Source Code.":link "https://git.ch-naseem.com/noid-linux" \
--field="Support!Support Matrix channel.":link "https://matrix.to/#/#noid-support:ch-naseem.com" \
--button="  Exit!exit!gtk-cancel:1"

rm -f ~/.config/autostart/noid-welcome.desktop
