#!/usr/bin/env bash
set -euo pipefail

. $SCRIPTS_DIR/common.sh

oxidize_system() {
    clear

    summary="
This tweak will install Rust and some useful CLIs, in the process it will:
- Install rustup
- Install these CLIs: ripgrep, bat, fd-find, zoxide, eza, tealdeer, du-dust, bottom, cargo-update
- Modify these files: ~/.zshrc, ~/.bashrc"

    aliases_conf="
    alias \\
      ls='eza --icons=always --group-directories-first' \\
      ll='ls -la --git' \\
      tree='ls -Ta -I \".git\"' \\
      cat='bat --style plain --color=always' \\
      cd='z' \\
      cargo-update='cargo install-update -a'
    "

    echo "$banner"
    echo "$summary"

    read -p "Continue? [y/N] " -r response

    [[ "$response" == [yY] ]] || { echo "Cancelled." && exit 1; }

    echo "Installing Rust toolchain..."
    if ! curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh; then
        echo "Rust installation failed. Exiting."
        exit 1
    fi

    echo "Installing CLI tools..."
    if ! sudo xbps-install -Sy ripgrep bat fd zoxide eza tealdeer dust bottom cargo-update; then
        echo "CLI tools installation failed. Exiting."
        exit 1
    fi

    echo "Adding aliases to shell configs..."

    if grep -q 'AUTO-GENERATED BY NOID TWEAKS' ~/.zshrc || grep -q 'AUTO-GENERATED BY NOID TWEAKS' ~/.bashrc; then
        echo "Aliases already configured. Skipping setup."
    else
        echo "$header$aliases_conf$footer" | tee -a ~/.zshrc
        echo "$header$aliases_conf$footer" | tee -a ~/.bashrc
    fi

    echo "Setup complete."
}
export -f oxidize_system

alacritty --hold -e bash -c oxidize_system
