#!/usr/bin/env bash

set -euo pipefail
clear

banner="
 /\$\$   /\$\$  /\$\$\$\$\$\$  /\$\$\$\$\$\$ /\$\$\$\$\$\$\$        /\$\$\$\$\$\$\$\$ /\$\$      /\$\$ /\$\$\$\$\$\$\$\$  /\$\$\$\$\$\$  /\$\$   /\$\$  /\$\$\$\$\$\$
| \$\$\$ | \$\$ /\$\$__  \$\$|_  \$\$_/| \$\$__  \$\$      |__  \$\$__/| \$\$  /\$ | \$\$| \$\$_____/ /\$\$__  \$\$| \$\$  /\$\$/ /\$\$__  \$\$
| \$\$\$\$| \$\$| \$\$  \\ \$\$  | \$\$  | \$\$  \\ \$\$         | \$\$   | \$\$ /\$\$\$| \$\$| \$\$      | \$\$  \\ \$\$| \$\$ /\$\$/ | \$\$  \\__/
| \$\$ \$\$ \$\$| \$\$  | \$\$  | \$\$  | \$\$  | \$\$         | \$\$   | \$\$/\$\$ \$\$ \$\$| \$\$\$\$\$   | \$\$\$\$\$\$\$\$| \$\$\$\$\$/  |  \$\$\$\$\$\$
| \$\$  \$\$\$\$| \$\$  | \$\$  | \$\$  | \$\$  | \$\$         | \$\$   | \$\$\$\$_  \$\$\$\$| \$\$__/   | \$\$__  \$\$| \$\$  \$\$   \\____  \$\$
| \$\$\\  \$\$\$| \$\$  | \$\$  | \$\$  | \$\$  | \$\$         | \$\$   | \$\$\$/ \\  \$\$\$| \$\$      | \$\$  | \$\$| \$\$\\  \$\$  /\$\$  \\ \$\$
| \$\$ \\  \$\$|  \$\$\$\$\$\$/ /\$\$\$\$\$\$| \$\$\$\$\$\$\$/         | \$\$   | \$\$/   \\  \$\$| \$\$\$\$\$\$\$\$| \$\$  | \$\$| \$\$ \\  \$\$|  \$\$\$\$\$\$/
|__/  \\__/ \\______/ |______/|_______/          |__/   |__/     \\__/|________/|__/  |__/|__/  \\__/ \\______/
"

summary="
This tweak will install virt-manager, in the process it will:
- Install these deps: qemu, virt-manager, virt-viewer, dnsmasq, vde2, bridge-utils, openbsd-netcat, libguestfs
- Enable these Runit services: libvirtd, virtlogd
- Modify these files: /etc/libvirt/libvirtd.conf, /etc/libvirt/qemu.conf
- Add your user to the libvirt user group.

And you will need to restart for changes to take effect."

header="
# === AUTO-GENERATED BY NOID TWEAKS ===
"

footer="
# ========== END NOID TWEAK ==========="


libvirtd_conf="
unix_sock_group = \"libvirt\"
unix_sock_ro_perms = \"0777\"
unix_sock_rw_perms = \"0770\"
"

qemu_conf="
user = \"$USER\"
group = \"$USER\"
"

echo "$banner"
echo "$summary"

read -p "Continue? [y/N] " -r response

[[ "$response" == [yY] ]] || { echo "Cancelled." && exit 1; }

sudo -v

echo "Installing virtualization packages..."
if ! sudo xbps-install -Sy qemu virt-manager virt-viewer dnsmasq vde2 bridge-utils openbsd-netcat libguestfs; then
  echo "Package installation failed. Exiting."
  exit 1
fi

echo "Starting services..."
sudo ln -sf /etc/sv/libvirtd /var/service
sudo ln -sf /etc/sv/virtlogd /var/service

echo "Configuring libvirtd..."

if grep -q 'AUTO-GENERATED BY NOID TWEAKS' /etc/libvirt/libvirtd.conf; then
  echo "Configuration already applied. Skipping setup."
else
  echo "$header$libvirtd_conf$footer" | sudo tee -a /etc/libvirt/libvirtd.conf > /dev/null
fi


echo "Configuring qemu..."

if grep -q 'AUTO-GENERATED BY NOID TWEAKS' /etc/libvirt/qemu.conf; then
  echo "Configuration already applied. Skipping setup."
else
  echo "$header$qemu_conf$footer" | sudo tee -a /etc/libvirt/qemu.conf > /dev/null
fi

echo "Adding user to libvirt group..."
sudo usermod -aG libvirt "$USER"

echo "Setup complete. Restart your system for changes to fully take effect."
